export const MIRROR_DEFAULTS = {
  goalCLP: 600000000,
  monthlyContributionCLP: 200000,
  cashCLP: 1874,
  cashUSD: 0,
  horizonYear: 2030,
  crypto: {
    BTC: {
      ticker: 'BTC',
      marketId: 'btc-clp',
      name: 'Bitcoin',
      shortName: 'Bitcoin',
      currency: 'CLP',
      shares: 0.04047219,
      averageCost: 29161672.92,
      averageCostEstimated: true,
      costBasisMethod: 'Costo reconstruido: tramo histórico sin costo documentado valorizado al precio de la primera compra registrada.',
      fallbackPrice: 77591032.26,
      platform: 'Buda',
      custodian: 'Buda.com',
      role: 'Cripto existente · en estudio',
      risk: 'Muy alto',
      accent: '#f3b85b',
    },
    ETH: {
      ticker: 'ETH',
      marketId: 'eth-clp',
      name: 'Ethereum',
      shortName: 'Ethereum',
      currency: 'CLP',
      shares: 1.568461619,
      averageCost: 1801099.82,
      averageCostEstimated: false,
      costBasisMethod: 'Costo promedio reconstruido desde el historial posterior al reinicio de saldo.',
      fallbackPrice: 2505049.50,
      platform: 'Buda',
      custodian: 'Buda.com',
      role: 'Cripto existente · en estudio',
      risk: 'Muy alto',
      accent: '#9c7cff',
    },
  },
  assets: {
    VOO: {
      ticker: 'VOO',
      marketSymbol: 'VOO',
      name: 'Vanguard S&P 500 ETF',
      shortName: 'S&P 500',
      currency: 'USD',
      shares: 9.43928896,
      averageCost: 669.17,
      dividends: 27.68,
      targetWeight: 60,
      fallbackPrice: 679.14,
      role: 'Núcleo',
      risk: 'Medio',
      thesis: 'Base diversificada del portafolio y principal motor de crecimiento de largo plazo.',
      scenarioReturns: { conservative: 5, base: 9, optimistic: 12 },
      accent: '#7c9cff',
    },
    SMH: {
      ticker: 'SMH',
      marketSymbol: 'SMH',
      name: 'VanEck Semiconductor ETF',
      shortName: 'Semiconductores',
      currency: 'USD',
      shares: 3.86000929,
      averageCost: 590.27,
      dividends: 0,
      targetWeight: 20,
      fallbackPrice: 540.53,
      role: 'Acelerador',
      risk: 'Alto',
      thesis: 'Exposición concentrada al ciclo global de chips, infraestructura de IA y fabricantes líderes.',
      scenarioReturns: { conservative: 3, base: 12, optimistic: 18 },
      accent: '#9c7cff',
    },
    BCH: {
      ticker: 'BCH',
      marketSymbol: 'BCH',
      name: 'Banco de Chile ADR',
      shortName: 'Banca chilena',
      currency: 'USD',
      shares: 14.17875002,
      averageCost: 37.48,
      dividends: 30.83,
      targetWeight: 5,
      fallbackPrice: 40.72,
      role: 'Chile / dividendos',
      risk: 'Medio',
      thesis: 'Exposición local rentable, con componente de dividendos y riesgo país concentrado.',
      scenarioReturns: { conservative: 3, base: 7, optimistic: 10 },
      accent: '#28d9a7',
    },
    CFIETFGE: {
      ticker: 'CFIETFGE',
      marketSymbol: 'CFIETFGE.SN',
      name: 'ETF Acciones Globales',
      shortName: 'Acciones globales',
      currency: 'CLP',
      shares: 431,
      averageCost: 1624.63,
      averageCostEstimated: true,
      dividends: 393,
      targetWeight: 15,
      fallbackPrice: 3247.15,
      role: 'Diversificación global',
      risk: 'Medio',
      thesis: 'Diversificación internacional en pesos y tratamiento tributario local 107 LIR.',
      scenarioReturns: { conservative: 4, base: 8, optimistic: 11 },
      accent: '#f3b85b',
    },
  },
};

export const PURCHASES = {
  VOO: [
    { date: '2026-06-30', amount: 15.71, currency: 'USD', label: 'Reinversión dividendo' },
  ],
  SMH: [
    { date: '2026-06-22', amount: 546.82, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-07-13', amount: 213.31, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-07-31', amount: 200.00, shares: 0.36634813, price: 545.93, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-08-03', amount: 119.84, shares: 0.22740089, price: 527.00, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-08-10', amount: 108.93, shares: 0.18958895, price: 574.56, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-08-19', amount: 64.70, shares: 0.11500815, price: 562.57, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-08-31', amount: 106.34, shares: 0.19101548, price: 556.71, currency: 'USD', label: 'Compra SMH' },
    { date: '2026-09-14', amount: 103.51, shares: 0.19045120, price: 543.50, currency: 'USD', label: 'Compra SMH' },
  ],
  BCH: [
    { date: '2025-11-26', amount: 531.36, currency: 'USD', label: 'Compra BCH' },
  ],
  CFIETFGE: [],
};

export const RANGE_OPTIONS = [
  { key: '1d', label: '1 día' },
  { key: '1m', label: '1 mes' },
  { key: '1y', label: '1 año' },
  { key: '5y', label: '5 años' },
];

export function getAssetConfig(ticker) {
  return MIRROR_DEFAULTS.assets[ticker] || null;
}
